apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
  namespace: default
spec:
  clusterIP: 
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: drupal-mysql
  type: ClusterIP
